
mod TEST-PLS-MATCHING is
  pr MMATCHING .
  pr PLS-MM .
endm

set trace off .

***(
---- test-1
red mmatch(
    'TEST-PLS-MATCHING,
    < Server:Oid : EClass | eStructuralFeatures : (In@Server:Oid, Out@Server:Oid, Oids1:Set{Oid}), Atts1:AttributeSet >,
    < machine@devsmm : EClass | name : "Machine", eSuperTypes : positionedEl@devsmm,
                                eStructuralFeatures : (pt@machine@devsmm, 
                                                       defectiverate@machine@devsmm, 
                                                       in@machine@devsmm,
                                                       out@machine@devsmm) >) .
---- test-2
red mmatch(
    'TEST-PLS-MATCHING,
    < Server:Oid : EClass | eStructuralFeatures : (In@Server:Oid, Out@Server:Oid, Oids1:Set{Oid}), Atts1:AttributeSet >
    < In@Server:Oid : EReference | lowerBound : 0, upperBound : 1, eType : Queue:Oid, containment : false, Atts4:AttributeSet >
    < Out@Server:Oid : EReference | lowerBound : 1, upperBound : 1, eType : Queue:Oid, containment : false, Atts5:AttributeSet >
    C:Configuration,
    
    < machine@devsmm : EClass | name : "Machine", eSuperTypes : positionedEl@devsmm,
                                eStructuralFeatures : (pt@machine@devsmm, 
                                                       defectiverate@machine@devsmm, 
                                                       in@machine@devsmm,
                                                       out@machine@devsmm) >
    < pt@machine@devsmm : EAttribute | name : "pt", lowerBound : 1, upperBound : 1, eType : Int >
    < defectiverate@machine@devsmm : EAttribute | name : "defectiverate", lowerBound : 1, upperBound : 1, eType : Int >
    < in@machine@devsmm : EReference | name : "in", lowerBound : 0, upperBound : 1, 
                                       eType : limitedContainer@devsmm, containment : false >
    < out@machine@devsmm : EReference | name : "out", lowerBound : 1, upperBound : 1,
                                        eType : limitedContainer@devsmm, containment : false >
    < generator@devsmm : EClass | name : "Generator", eSuperTypes : machine@devsmm, eStructuralFeatures : empty >) .
--- end block comment )

---- final test
red mmatch(
    'TEST-PLS-MATCHING,
    < Server:Oid : EClass | eStructuralFeatures : (In@Server:Oid, Out@Server:Oid, Oids1:Set{Oid}), Atts1:AttributeSet >
    < In@Server:Oid : EReference | lowerBound : 0, upperBound : 1, eType : Queue:Oid, containment : false, Atts4:AttributeSet >
    < Out@Server:Oid : EReference | lowerBound : 1, upperBound : 1, eType : Queue:Oid, containment : false, Atts5:AttributeSet >
    < Queue:Oid : EClass | eStructuralFeatures : (Reqsts@Queue:Oid, Oids2:Set{Oid}), Atts2:AttributeSet >
    < Reqsts@Queue:Oid : EReference | lowerBound : 0, upperBound : *, eType : Request:Oid, containment : true, Atts6:AttributeSet >
    < Request:Oid : EClass | Atts3:AttributeSet >
    C:Configuration,
    plsmm,
    upTerm(('Server:Oid 'Queue:Oid 'Request:Oid)) ) .

red size(mmatch(
    'TEST-PLS-MATCHING,
    < Server:Oid : EClass | eStructuralFeatures : (In@Server:Oid, Out@Server:Oid, Oids1:Set{Oid}), Atts1:AttributeSet >
    < In@Server:Oid : EReference | lowerBound : 0, upperBound : 1, eType : Queue:Oid, containment : false, Atts4:AttributeSet >
    < Out@Server:Oid : EReference | lowerBound : 1, upperBound : 1, eType : Queue:Oid, containment : false, Atts5:AttributeSet >
    < Queue:Oid : EClass | eStructuralFeatures : (Reqsts@Queue:Oid, Oids2:Set{Oid}), Atts2:AttributeSet >
    < Reqsts@Queue:Oid : EReference | lowerBound : 0, upperBound : *, eType : Request:Oid, containment : true, Atts6:AttributeSet >
    < Request:Oid : EClass | Atts3:AttributeSet >
    C:Configuration,
    plsmm,
    upTerm((Server:Oid Queue:Oid Request:Oid)))) .
    
eof 
red metaMatch(upModule('TEST-PLS-MATCHING, true),
    upTerm(< Server:Oid : EClass | eStructuralFeatures : (In@Server:Oid, Out@Server:Oid, Oids1:Set{Oid}), Atts1:AttributeSet >
    < In@Server:Oid : EReference | lowerBound : 0, upperBound : 1, eType : Queue:Oid, containment : false, Atts4:AttributeSet >
    < Out@Server:Oid : EReference | lowerBound : 1, upperBound : 1, eType : Queue:Oid, containment : false, Atts5:AttributeSet >
    < Queue:Oid : EClass | eStructuralFeatures : (Reqsts@Queue:Oid, Oids2:Set{Oid}), Atts2:AttributeSet >
    < Reqsts@Queue:Oid : EReference | lowerBound : 0, upperBound : *, eType : Request:Oid, containment : true, Atts6:AttributeSet >
    < Request:Oid : EClass | Atts3:AttributeSet >
    C:Configuration),
    '__['<_:_|_>['assemble@devsmm.Oid,'EClass.EClass,'_`,_['_:_[
        'eStructuralFeatures.ReferenceName,'_`,_['defectiverate@machine@devsmm.Oid,
        'in@machine@devsmm.Oid,'out@machine@devsmm.Oid,'pt@machine@devsmm.Oid]],'_:_[
        'eSuperTypes.ReferenceName,'machine@devsmm.Oid],'_:_['name.AttributeName,
        '"Assemble".String]]],'<_:_|_>['capacity@limitedContainer@devsmm.Oid,
        'EAttribute.EAttribute,'_`,_['_:_['eType.ReferenceName,'Int.OclType],'_:_[
        'lowerBound.AttributeName,'s_['0.Zero]],'_:_['name.AttributeName,'"capacity".String],
        '_:_['upperBound.AttributeName,'s_['0.Zero]]]],'<_:_|_>['container@devsmm.Oid,
        'EClass.EClass,'_`,_['_:_['eStructuralFeatures.ReferenceName,
        'parts@container@devsmm.Oid],'_:_['eSuperTypes.ReferenceName,'positionedEl@devsmm.Oid],
        '_:_['name.AttributeName,'"Container".String]]],'<_:_|_>['conveyor@devsmm.Oid,
        'EClass.EClass,'_`,_['_:_['eStructuralFeatures.ReferenceName,'_`,_[
        'capacity@limitedContainer@devsmm.Oid,'outParts@conveyor@devsmm.Oid,
        'parts@container@devsmm.Oid]],'_:_['eSuperTypes.ReferenceName,
        'limitedContainer@devsmm.Oid],'_:_['name.AttributeName,'"Conveyor".String]]],'<_:_|_>[
        'defective@part@devsmm.Oid,'EAttribute.EAttribute,'_`,_['_:_['eType.ReferenceName,
        'Boolean.OclType],'_:_['lowerBound.AttributeName,'s_['0.Zero]],'_:_['name.AttributeName,
        '"deffective".String],'_:_['upperBound.AttributeName,'s_['0.Zero]]]],'<_:_|_>[
        'defectiverate@machine@devsmm.Oid,'EAttribute.EAttribute,'_`,_['_:_['eType.ReferenceName,
        'Int.OclType],'_:_['lowerBound.AttributeName,'s_['0.Zero]],'_:_['name.AttributeName,
        '"defectiverate".String],'_:_['upperBound.AttributeName,'s_['0.Zero]]]],'<_:_|_>[
        'els@plant@devsmm.Oid,'EReference.EReference,'_`,_['_:_['containment.AttributeName,
        'true.Bool],'_:_['eOpposite.ReferenceName,'null.OclVoid],'_:_['eType.ReferenceName,
        'positionedEl@devsmm.Oid],'_:_['lowerBound.AttributeName,'0.Zero],'_:_[
        'name.AttributeName,'"els".String],'_:_['upperBound.AttributeName,'*.Nat]]],'<_:_|_>[
        'genHandle@devsmm.Oid,'EClass.EClass,'_`,_['_:_['eStructuralFeatures.ReferenceName,'_`,_[
        'defectiverate@machine@devsmm.Oid,'in@machine@devsmm.Oid,'out@machine@devsmm.Oid,
        'pt@machine@devsmm.Oid]],'_:_['eSuperTypes.ReferenceName,'generator@devsmm.Oid],'_:_[
        'name.AttributeName,'"GenHandle".String]]],'<_:_|_>['genHead@devsmm.Oid,'EClass.EClass,
        '_`,_['_:_['eStructuralFeatures.ReferenceName,'_`,_['defectiverate@machine@devsmm.Oid,
        'in@machine@devsmm.Oid,'out@machine@devsmm.Oid,'pt@machine@devsmm.Oid]],'_:_[
        'eSuperTypes.ReferenceName,'generator@devsmm.Oid],'_:_['name.AttributeName,
        '"GenHead".String]]],'<_:_|_>['generator@devsmm.Oid,'EClass.EClass,'_`,_['_:_[
        'eStructuralFeatures.ReferenceName,'_`,_['defectiverate@machine@devsmm.Oid,
        'in@machine@devsmm.Oid,'out@machine@devsmm.Oid,'pt@machine@devsmm.Oid]],'_:_[
        'eSuperTypes.ReferenceName,'machine@devsmm.Oid],'_:_['name.AttributeName,
        '"Generator".String]]],'<_:_|_>['hammer@devsmm.Oid,'EClass.EClass,'_`,_['_:_[
        'eStructuralFeatures.ReferenceName,'defective@part@devsmm.Oid],'_:_[
        'eSuperTypes.ReferenceName,'part@devsmm.Oid],'_:_['name.AttributeName,
        '"Hammer".String]]],'<_:_|_>['handle@devsmm.Oid,'EClass.EClass,'_`,_['_:_[
        'eStructuralFeatures.ReferenceName,'defective@part@devsmm.Oid],'_:_[
        'eSuperTypes.ReferenceName,'part@devsmm.Oid],'_:_['name.AttributeName,
        '"Handle".String]]],'<_:_|_>['head@devsmm.Oid,'EClass.EClass,'_`,_['_:_[
        'eStructuralFeatures.ReferenceName,'defective@part@devsmm.Oid],'_:_[
        'eSuperTypes.ReferenceName,'part@devsmm.Oid],'_:_['name.AttributeName,'"Head".String]]],
        '<_:_|_>['in@machine@devsmm.Oid,'EReference.EReference,'_`,_['_:_[
        'containment.AttributeName,'false.Bool],'_:_['eType.ReferenceName,
        'limitedContainer@devsmm.Oid],'_:_['lowerBound.AttributeName,'0.Zero],'_:_[
        'name.AttributeName,'"in".String],'_:_['upperBound.AttributeName,'s_['0.Zero]]]],
        '<_:_|_>['limitedContainer@devsmm.Oid,'EClass.EClass,'_`,_['_:_[
        'eStructuralFeatures.ReferenceName,'_`,_['capacity@limitedContainer@devsmm.Oid,
        'parts@container@devsmm.Oid]],'_:_['eSuperTypes.ReferenceName,'container@devsmm.Oid],
        '_:_['name.AttributeName,'"LimitedContainer".String]]],'<_:_|_>['machine@devsmm.Oid,
        'EClass.EClass,'_`,_['_:_['eStructuralFeatures.ReferenceName,'_`,_[
        'defectiverate@machine@devsmm.Oid,'in@machine@devsmm.Oid,'out@machine@devsmm.Oid,
        'pt@machine@devsmm.Oid]],'_:_['eSuperTypes.ReferenceName,'positionedEl@devsmm.Oid],'_:_[
        'name.AttributeName,'"Machine".String]]],'<_:_|_>['out@machine@devsmm.Oid,
        'EReference.EReference,'_`,_['_:_['containment.AttributeName,'false.Bool],'_:_[
        'eType.ReferenceName,'limitedContainer@devsmm.Oid],'_:_['lowerBound.AttributeName,'s_[
        '0.Zero]],'_:_['name.AttributeName,'"out".String],'_:_['upperBound.AttributeName,'s_[
        '0.Zero]]]],'<_:_|_>['outParts@conveyor@devsmm.Oid,'EReference.EReference,'_`,_['_:_[
        'containment.AttributeName,'true.Bool],'_:_['eOpposite.ReferenceName,'null.OclVoid],'_:_[
        'eType.ReferenceName,'part@devsmm.Oid],'_:_['lowerBound.AttributeName,'0.Zero],'_:_[
        'name.AttributeName,'"outParts".String],'_:_['upperBound.AttributeName,'*.Nat]]],
        '<_:_|_>['part@devsmm.Oid,'EClass.EClass,'_`,_['_:_['eStructuralFeatures.ReferenceName,
        'defective@part@devsmm.Oid],'_:_['eSuperTypes.ReferenceName,'positionedEl@devsmm.Oid],
        '_:_['name.AttributeName,'"Part".String]]],'<_:_|_>['parts@container@devsmm.Oid,
        'EReference.EReference,'_`,_['_:_['containment.AttributeName,'true.Bool],'_:_[
        'eOpposite.ReferenceName,'null.OclVoid],'_:_['eType.ReferenceName,'part@devsmm.Oid],'_:_[
        'lowerBound.AttributeName,'0.Zero],'_:_['name.AttributeName,'"els".String],'_:_[
        'upperBound.AttributeName,'*.Nat]]],'<_:_|_>['plant@devsmm.Oid,'EClass.EClass,'_`,_['_:_[
        'eStructuralFeatures.ReferenceName,'els@plant@devsmm.Oid],'_:_['name.AttributeName,
        '"Plant".String]]],'<_:_|_>['positionedEl@devsmm.Oid,'EClass.EClass,'_`,_['_:_[
        'eStructuralFeatures.ReferenceName,'empty.Set`{Oid`}],'_:_['name.AttributeName,
        '"PositionedEl".String]]],'<_:_|_>['pt@machine@devsmm.Oid,'EAttribute.EAttribute,'_`,_[
        '_:_['eType.ReferenceName,'Int.OclType],'_:_['lowerBound.AttributeName,'s_['0.Zero]],
        '_:_['name.AttributeName,'"pt".String],'_:_['upperBound.AttributeName,'s_['0.Zero]]]],
        '<_:_|_>['tray@devsmm.Oid,'EClass.EClass,'_`,_['_:_['eStructuralFeatures.ReferenceName,
        '_`,_['capacity@limitedContainer@devsmm.Oid,'parts@container@devsmm.Oid]],'_:_[
        'eSuperTypes.ReferenceName,'limitedContainer@devsmm.Oid],'_:_['name.AttributeName,
        '"Tray".String]]],'<_:_|_>['user@devsmm.Oid,'EClass.EClass,'_`,_['_:_[
        'eStructuralFeatures.ReferenceName,'parts@container@devsmm.Oid],'_:_[
        'eSuperTypes.ReferenceName,'container@devsmm.Oid],'_:_['name.AttributeName,
        '"User".String]]]], nil, 0) .