---- ----------------------------------------------- ----
---- Programmatically generated code using e-Motions ----
---- @date Wed Sep 24 10:46:26 CEST 2014             ----
---- ----------------------------------------------- ----

mod @DEVSMM@BEHAVIOR@ is
  pr E-MOTIONS .
  pr DISCRETE_TIME .
  pr @DEVSMM@ .
    
  op els@OCLSf : -> @StructuralFeature  .
  op prodTime@OCLSf : -> @StructuralFeature  .
  op defRate@OCLSf : -> @StructuralFeature  .
  op in@OCLSf : -> @StructuralFeature  .
  op out@OCLSf : -> @StructuralFeature  .
  op counter@OCLSf : -> @StructuralFeature  .
  op flRt@OCLSf : -> @StructuralFeature  .
  op parts@OCLSf : -> @StructuralFeature  .
  op speed@OCLSf : -> @StructuralFeature  .
  op out@OCLSf : -> @StructuralFeature  .
  op outParts@OCLSf : -> @StructuralFeature  .
  op capacity@OCLSf : -> @StructuralFeature  .
  op defective@OCLSf : -> @StructuralFeature  .
  op numFailures@OCLSf : -> @StructuralFeature  .
  op numTotal@OCLSf : -> @StructuralFeature  .
  op rate@OCLSf : -> @StructuralFeature  .
  op reqResults@OCLSf : -> @StructuralFeature  .
  op currentExec@GenHandle : Set @Model -> Bool  .
  op currentExec@GenHead : Set @Model -> Bool  .
  op currentExec@Carry : Set @Model -> Bool  .
  op notconcurrentassembles@Assemble : Set Set{@Object} @Model -> Bool  .
  op currentExec@Assemble : Set @Model -> Bool  .
  op currentExec@FailureRate1 : Set @Model -> Bool  .
  op currentExec@FailureRate2 : Set @Model -> Bool  .
  op e : -> Vid  .
  op noconc@Collect : Set Set{@Object} @Model -> Bool  .
    
  eq name(els@OCLSf)
    = "els" .
  eq name(prodTime@OCLSf)
    = "prodTime" .
  eq name(defRate@OCLSf)
    = "defRate" .
  eq name(in@OCLSf)
    = "in" .
  eq name(out@OCLSf)
    = "out" .
  eq name(counter@OCLSf)
    = "counter" .
  eq name(flRt@OCLSf)
    = "flRt" .
  eq name(parts@OCLSf)
    = "parts" .
  eq name(speed@OCLSf)
    = "speed" .
  eq name(out@OCLSf)
    = "out" .
  eq name(outParts@OCLSf)
    = "outParts" .
  eq name(capacity@OCLSf)
    = "capacity" .
  eq name(defective@OCLSf)
    = "defective" .
  eq name(numFailures@OCLSf)
    = "numFailures" .
  eq name(numTotal@OCLSf)
    = "numTotal" .
  eq name(rate@OCLSf)
    = "rate" .
  eq name(reqResults@OCLSf)
    = "reqResults" .
  eq rulesInformation
    = _`{_`}(@MGBehavior@, 
      __(
        <_:_|_>('Rule0:OCL-Type, AtomicRule@MGBehavior, 
          _#_(
            _:_(name@Rule@MGBehavior, "GenHandle"), 
            _:_(lowerBound@Rule@MGBehavior, null), 
            _:_(upperBound@Rule@MGBehavior, null), 
            _:_(soft@Rule@MGBehavior, false), 
            _:_(periodicity@AtomicRule@MGBehavior, null))), 
        <_:_|_>('Rule0:OCL-Type, AtomicRule@MGBehavior, 
          _#_(
            _:_(name@Rule@MGBehavior, "GenHead"), 
            _:_(lowerBound@Rule@MGBehavior, null), 
            _:_(upperBound@Rule@MGBehavior, null), 
            _:_(soft@Rule@MGBehavior, false), 
            _:_(periodicity@AtomicRule@MGBehavior, null))), 
        <_:_|_>('Rule0:OCL-Type, AtomicRule@MGBehavior, 
          _#_(
            _:_(name@Rule@MGBehavior, "Carry"), 
            _:_(lowerBound@Rule@MGBehavior, null), 
            _:_(upperBound@Rule@MGBehavior, null), 
            _:_(soft@Rule@MGBehavior, false), 
            _:_(periodicity@AtomicRule@MGBehavior, null))), 
        <_:_|_>('Rule0:OCL-Type, AtomicRule@MGBehavior, 
          _#_(
            _:_(name@Rule@MGBehavior, "Transfer"), 
            _:_(lowerBound@Rule@MGBehavior, null), 
            _:_(upperBound@Rule@MGBehavior, null), 
            _:_(soft@Rule@MGBehavior, false), 
            _:_(periodicity@AtomicRule@MGBehavior, null))), 
        <_:_|_>('Rule0:OCL-Type, AtomicRule@MGBehavior, 
          _#_(
            _:_(name@Rule@MGBehavior, "Assemble"), 
            _:_(lowerBound@Rule@MGBehavior, null), 
            _:_(upperBound@Rule@MGBehavior, null), 
            _:_(soft@Rule@MGBehavior, false), 
            _:_(periodicity@AtomicRule@MGBehavior, null))), 
        <_:_|_>('Rule0:OCL-Type, AtomicRule@MGBehavior, 
          _#_(
            _:_(name@Rule@MGBehavior, "Collect"), 
            _:_(lowerBound@Rule@MGBehavior, null), 
            _:_(upperBound@Rule@MGBehavior, null), 
            _:_(soft@Rule@MGBehavior, false), 
            _:_(periodicity@AtomicRule@MGBehavior, null))), 
        <_:_|_>('Rule0:OCL-Type, AtomicRule@MGBehavior, 
          _#_(
            _:_(name@Rule@MGBehavior, "CreateFailure"), 
            _:_(lowerBound@Rule@MGBehavior, null), 
            _:_(upperBound@Rule@MGBehavior, null), 
            _:_(soft@Rule@MGBehavior, false), 
            _:_(periodicity@AtomicRule@MGBehavior, null))))) .
  eq currentExec@GenHandle(Set`{_`}(_;_(hg:OCL-Type, c:OCL-Type)), _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "GenHandle"), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(L@ACTEXEC@:MSet{OCL-Exp}, OR1@:Oid, OR2@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, hg:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "hg"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "c"))))))
    = true .
  eq currentExec@GenHandle(OIDSET@:Set, MODEL@:@Model)
    = false [owise] .
  ceq mte(_`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(hg:OCL-Type, GENHANDLE@DEVSMM@hg@CLASS:GenHandle@devsmm, 
        _#_(
          _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object})))
    = 0
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(hg:OCL-Type, GENHANDLE@DEVSMM@hg@CLASS:GenHandle@devsmm, 
          _#_(
            _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
    /\ _in_(c:OCL-Type, OUT@hg@ATT:OCL-Type)
    /\ VAR1@:Oid := newId(_+_(VALUE@ids@:Int, 3))
    /\ VAR2@:Oid := newId(_+_(VALUE@ids@:Int, 4))
    /\ prodTime:OCL-Type := eval(_+_(_-_(
      __(hg:OCL-Type, ._(prodTime@OCLSf)), 3), _rem_(random(_+_(VALUE@rdm@:Int, 2)), eval(6, env(empty), MODEL@:@Model))), env(empty), MODEL@:@Model)
    /\ rdm:OCL-Type := eval(_rem_(random(_+_(VALUE@rdm@:Int, 3)), eval(100, env(empty), MODEL@:@Model)), env(empty), MODEL@:@Model)
    /\ eval(_and_(_>_(__(hg:OCL-Type, ._(counter@OCLSf)), 0), _<_(_+_(_->`size`(`)(__(c:OCL-Type, ._(parts@OCLSf))), _->`size`(`)(__(c:OCL-Type, ._(outParts@OCLSf)))), __(c:OCL-Type, ._(capacity@OCLSf)))), env(empty), MODEL@:@Model)
    /\ not_(currentExec@GenHandle(Set`{_`}(_;_(hg:OCL-Type, c:OCL-Type)), MODEL@:@Model)) .
  eq currentExec@GenHead(Set`{_`}(_;_(hg:OCL-Type, c:OCL-Type)), _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "GenHead"), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(L@ACTEXEC@:MSet{OCL-Exp}, OR1@:Oid, OR2@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, hg:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "hg"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "c"))))))
    = true .
  eq currentExec@GenHead(OIDSET@:Set, MODEL@:@Model)
    = false [owise] .
  ceq mte(_`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(hg:OCL-Type, GENHEAD@DEVSMM@hg@CLASS:GenHead@devsmm, 
        _#_(
          _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object})))
    = 0
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(hg:OCL-Type, GENHEAD@DEVSMM@hg@CLASS:GenHead@devsmm, 
          _#_(
            _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
    /\ _in_(c:OCL-Type, OUT@hg@ATT:OCL-Type)
    /\ VAR1@:Oid := newId(_+_(VALUE@ids@:Int, 3))
    /\ VAR2@:Oid := newId(_+_(VALUE@ids@:Int, 4))
    /\ prodTime:OCL-Type := eval(_+_(_-_(
      __(hg:OCL-Type, ._(prodTime@OCLSf)), 3), _rem_(random(_+_(VALUE@rdm@:Int, 6)), eval(6, env(empty), MODEL@:@Model))), env(empty), MODEL@:@Model)
    /\ rdm:OCL-Type := eval(_rem_(random(_+_(VALUE@rdm@:Int, 7)), eval(100, env(empty), MODEL@:@Model)), env(empty), MODEL@:@Model)
    /\ eval(_and_(_>_(__(hg:OCL-Type, ._(counter@OCLSf)), 0), _<_(_+_(_->`size`(`)(__(c:OCL-Type, ._(parts@OCLSf))), _->`size`(`)(__(c:OCL-Type, ._(outParts@OCLSf)))), __(c:OCL-Type, ._(capacity@OCLSf)))), env(empty), MODEL@:@Model)
    /\ not_(currentExec@GenHead(Set`{_`}(_;_(hg:OCL-Type, c:OCL-Type)), MODEL@:@Model)) .
  eq currentExec@Carry(Set`{_`}(_;_(p:OCL-Type, c:OCL-Type)), _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "Carry"), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(L@ACTEXEC@:MSet{OCL-Exp}, OR1@:Oid, OR2@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "p"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "c"))))))
    = true .
  eq currentExec@Carry(OIDSET@:Set, MODEL@:@Model)
    = false [owise] .
  ceq mte(_`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object})))
    = 0
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
    /\ _in_(p:OCL-Type, PARTS@c@ATT:OCL-Type)
    /\ not_(currentExec@Carry(Set`{_`}(_;_(p:OCL-Type, c:OCL-Type)), MODEL@:@Model)) .
  ceq notconcurrentassembles@Assemble(Set`{_`}(_;_(he:OCL-Type, ha:OCL-Type, t:OCL-Type, a:OCL-Type, c:OCL-Type, fr:OCL-Type)), __(<_:_|_>(VAR1@:Oid, Variable@MGBehavior, _#_(_:_(name@Variable@MGBehavior, "rdm"), _:_(value@Variable@MGBehavior, rdm:OCL-Type))), <_:_|_>(VAR2@:Oid, Variable@MGBehavior, _#_(_:_(name@Variable@MGBehavior, "prodTime"), _:_(value@Variable@MGBehavior, prodTime:OCL-Type)))), _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(asse:OCL-Type, AtomicActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "Assemble"), 
          _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(L@asse:MSet{OCL-Exp}, OR1@asse:Oid))), asse@SFS:Set{@StructuralFeatureInstance})), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@asse:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, a:OCL-Type), OR1@asse@SFS:Set{@StructuralFeatureInstance})))))
    = true
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(asse:OCL-Type, AtomicActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "Assemble"), 
            _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(L@asse:MSet{OCL-Exp}, OR1@asse:Oid))), asse@SFS:Set{@StructuralFeatureInstance})), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@asse:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, a:OCL-Type), OR1@asse@SFS:Set{@StructuralFeatureInstance})))) .
  eq notconcurrentassembles@Assemble(OIDSET@:Set, OBJSET@:Set{@Object}, MODEL@:@Model)
    = false [owise] .
  eq currentExec@Assemble(Set`{_`}(_;_(he:OCL-Type, ha:OCL-Type, t:OCL-Type, a:OCL-Type, c:OCL-Type, fr:OCL-Type)), _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "Assemble"), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(L@ACTEXEC@:MSet{OCL-Exp}, OR1@:Oid, OR2@:Oid, OR3@:Oid, OR4@:Oid, OR5@:Oid, OR6@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, he:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "he"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, ha:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "ha"))), 
      <_:_|_>(OR3@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, t:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "t"))), 
      <_:_|_>(OR4@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, a:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "a"))), 
      <_:_|_>(OR5@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "c"))), 
      <_:_|_>(OR6@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, fr:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "fr"))))))
    = true .
  eq currentExec@Assemble(OIDSET@:Set, MODEL@:@Model)
    = false [owise] .
  ceq mte(_`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(he:OCL-Type, HEAD@DEVSMM@he@CLASS:Head@devsmm, he@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(ha:OCL-Type, HANDLE@DEVSMM@ha@CLASS:Handle@devsmm, ha@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
        _#_(
          _:_(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type), 
          _:_(in@Machine@devsmm, IN@a@ATT:OCL-Type), 
          _:_(out@Machine@devsmm, OUT@a@ATT:OCL-Type), a@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(fr:OCL-Type, FAILURERATE@DEVSMM@fr@CLASS:FailureRate@devsmm, fr@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object})))
    = 0
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(he:OCL-Type, HEAD@DEVSMM@he@CLASS:Head@devsmm, he@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(ha:OCL-Type, HANDLE@DEVSMM@ha@CLASS:Handle@devsmm, ha@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
          _#_(
            _:_(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type), 
            _:_(in@Machine@devsmm, IN@a@ATT:OCL-Type), 
            _:_(out@Machine@devsmm, OUT@a@ATT:OCL-Type), a@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(fr:OCL-Type, FAILURERATE@DEVSMM@fr@CLASS:FailureRate@devsmm, fr@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
    /\ _in_(he:OCL-Type, PARTS@t@ATT:OCL-Type)
    /\ _in_(ha:OCL-Type, PARTS@t@ATT:OCL-Type)
    /\ _in_(t:OCL-Type, IN@a@ATT:OCL-Type)
    /\ _in_(c:OCL-Type, OUT@a@ATT:OCL-Type)
    /\ _in_(fr:OCL-Type, FLRT@a@ATT:OCL-Type)
    /\ VAR1@:Oid := newId(_+_(VALUE@ids@:Int, 7))
    /\ VAR2@:Oid := newId(_+_(VALUE@ids@:Int, 8))
    /\ rdm:OCL-Type := eval(_rem_(random(_+_(VALUE@rdm@:Int, 10)), eval(100, env(empty), MODEL@:@Model)), env(empty), MODEL@:@Model)
    /\ prodTime:OCL-Type := eval(_+_(_-_(
      __(a:OCL-Type, ._(prodTime@OCLSf)), 3), _rem_(random(_+_(VALUE@rdm@:Int, 11)), eval(6, env(empty), MODEL@:@Model))), env(empty), MODEL@:@Model)
    /\ eval(_<_(_+_(_->`size`(`)(__(c:OCL-Type, ._(parts@OCLSf))), _->`size`(`)(__(c:OCL-Type, ._(outParts@OCLSf)))), __(c:OCL-Type, ._(capacity@OCLSf))), env(empty), MODEL@:@Model)
    /\ not_(notconcurrentassembles@Assemble(Set`{_`}(_;_(he:OCL-Type, ha:OCL-Type, t:OCL-Type, a:OCL-Type, c:OCL-Type, fr:OCL-Type)), __(<_:_|_>(VAR1@:Oid, Variable@MGBehavior, _#_(_:_(name@Variable@MGBehavior, "rdm"), _:_(value@Variable@MGBehavior, rdm:OCL-Type))), <_:_|_>(VAR2@:Oid, Variable@MGBehavior, _#_(_:_(name@Variable@MGBehavior, "prodTime"), _:_(value@Variable@MGBehavior, prodTime:OCL-Type)))), MODEL@:@Model))
    /\ not_(currentExec@Assemble(Set`{_`}(_;_(he:OCL-Type, ha:OCL-Type, t:OCL-Type, a:OCL-Type, c:OCL-Type, fr:OCL-Type)), MODEL@:@Model)) .
  eq currentExec@FailureRate1(Set`{_`}(_;_(p:OCL-Type, o:OCL-Type)), _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(ACTEXEC@:Oid, OngoingActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "FailureRate1"), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(L@ACTEXEC@:MSet{OCL-Exp}, OR1@:Oid, OR2@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "p"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, o:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "o"))))))
    = true .
  eq currentExec@FailureRate1(OIDSET@:Set, MODEL@:@Model)
    = false [owise] .
  ceq mte(_`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
        _#_(
          _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object})))
    = 0
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
    /\ _in_(p:OCL-Type, REQRESULTS@o@ATT:OCL-Type)
    /\ eval(__(p:OCL-Type, ._(defective@OCLSf)), env(empty), MODEL@:@Model)
    /\ not_(currentExec@FailureRate1(Set`{_`}(_;_(p:OCL-Type, o:OCL-Type)), MODEL@:@Model)) .
  ceq applyOngoingRules(_`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
        _#_(
          _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), 
          _:_(numFailures@FailureRate@devsmm, NUMFAILURES@o@ATT:OCL-Type), 
          _:_(numTotal@FailureRate@devsmm, NUMTOTAL@o@ATT:OCL-Type), 
          _:_(rate@FailureRate@devsmm, RATE@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(ACTEXEC@:Oid, OngoingActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "FailureRate1"), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
          _:_(variables@ActionExec@MGBehavior, Set`{_`}(mt)), 
          _:_(maxTimer@ActionExec@MGBehavior, freeze(MAXDURATIONONGOING@:OCL-Exp)), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "p"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, o:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "o"))))), T:OCL-Type)
    = applyOngoingRules(readjust(Set`{_`}(mt), nil, _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(numFailures@FailureRate@devsmm, eval(_+_(
      __(o:OCL-Type, ._(numFailures@OCLSf)), 1), env(_<-_(self, o:OCL-Type)), MODEL@:@Model)), 
            _:_(numTotal@FailureRate@devsmm, eval(_+_(
      __(o:OCL-Type, ._(numTotal@OCLSf)), 1), env(_<-_(self, o:OCL-Type)), MODEL@:@Model)), 
            _:_(rate@FailureRate@devsmm, eval(_/_(_+_(
      __(o:OCL-Type, ._(numFailures@OCLSf)), 1), _+_(
      __(o:OCL-Type, ._(numTotal@OCLSf)), 1)), env(_<-_(self, o:OCL-Type)), MODEL@:@Model)), 
            _:_(reqResults@FailureRate@devsmm, update(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type, link(p:OCL-Type, null), nil)), o@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}))), T:OCL-Type)
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), 
            _:_(numFailures@FailureRate@devsmm, NUMFAILURES@o@ATT:OCL-Type), 
            _:_(numTotal@FailureRate@devsmm, NUMTOTAL@o@ATT:OCL-Type), 
            _:_(rate@FailureRate@devsmm, RATE@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(ACTEXEC@:Oid, OngoingActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "FailureRate1"), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(mt)), 
            _:_(maxTimer@ActionExec@MGBehavior, freeze(MAXDURATIONONGOING@:OCL-Exp)), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "p"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, o:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "o")))))
    /\ eval(__(p:OCL-Type, ._(defective@OCLSf)), env(empty), MODEL@:@Model)
    /\ _in_(p:OCL-Type, REQRESULTS@o@ATT:OCL-Type) .
  eq currentExec@FailureRate2(Set`{_`}(_;_(p:OCL-Type, o:OCL-Type)), _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(ACTEXEC@:Oid, OngoingActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "FailureRate2"), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(L@ACTEXEC@:MSet{OCL-Exp}, OR1@:Oid, OR2@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "p"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, o:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "o"))))))
    = true .
  eq currentExec@FailureRate2(OIDSET@:Set, MODEL@:@Model)
    = false [owise] .
  ceq mte(_`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
        _#_(
          _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object})))
    = 0
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
    /\ _in_(p:OCL-Type, REQRESULTS@o@ATT:OCL-Type)
    /\ eval(not_(__(p:OCL-Type, ._(defective@OCLSf))), env(empty), MODEL@:@Model)
    /\ not_(currentExec@FailureRate2(Set`{_`}(_;_(p:OCL-Type, o:OCL-Type)), MODEL@:@Model)) .
  ceq applyOngoingRules(_`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
        _#_(
          _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), 
          _:_(numTotal@FailureRate@devsmm, NUMTOTAL@o@ATT:OCL-Type), 
          _:_(rate@FailureRate@devsmm, RATE@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(ACTEXEC@:Oid, OngoingActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "FailureRate2"), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
          _:_(variables@ActionExec@MGBehavior, Set`{_`}(mt)), 
          _:_(maxTimer@ActionExec@MGBehavior, freeze(MAXDURATIONONGOING@:OCL-Exp)), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "p"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, o:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "o"))))), T:OCL-Type)
    = applyOngoingRules(readjust(Set`{_`}(mt), nil, _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(numTotal@FailureRate@devsmm, eval(_+_(
      __(o:OCL-Type, ._(numTotal@OCLSf)), 1), env(_<-_(self, o:OCL-Type)), MODEL@:@Model)), 
            _:_(rate@FailureRate@devsmm, eval(_/_(
      __(o:OCL-Type, ._(numFailures@OCLSf)), _+_(
      __(o:OCL-Type, ._(numTotal@OCLSf)), 1)), env(_<-_(self, o:OCL-Type)), MODEL@:@Model)), 
            _:_(reqResults@FailureRate@devsmm, update(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type, link(p:OCL-Type, null), nil)), o@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}))), T:OCL-Type)
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), 
            _:_(numTotal@FailureRate@devsmm, NUMTOTAL@o@ATT:OCL-Type), 
            _:_(rate@FailureRate@devsmm, RATE@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(ACTEXEC@:Oid, OngoingActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "FailureRate2"), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(mt)), 
            _:_(maxTimer@ActionExec@MGBehavior, freeze(MAXDURATIONONGOING@:OCL-Exp)), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "p"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, o:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "o")))))
    /\ eval(not_(__(p:OCL-Type, ._(defective@OCLSf))), env(empty), MODEL@:@Model)
    /\ _in_(p:OCL-Type, REQRESULTS@o@ATT:OCL-Type) .
  ceq mte(_`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
        _#_(
          _:_(outParts@Conveyor@devsmm, OUTPARTS@c@ATT:OCL-Type), 
          _:_(out@Conveyor@devsmm, OUT@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object})))
    = 0
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(outParts@Conveyor@devsmm, OUTPARTS@c@ATT:OCL-Type), 
            _:_(out@Conveyor@devsmm, OUT@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
    /\ _in_(t:OCL-Type, OUT@c@ATT:OCL-Type)
    /\ _in_(p:OCL-Type, OUTPARTS@c@ATT:OCL-Type)
    /\ eval(_and_(_<_(_->`size`(`)(__(t:OCL-Type, ._(parts@OCLSf))), __(t:OCL-Type, ._(capacity@OCLSf))), not_(_and_(_.=._(_->`size`(`)(__(t:OCL-Type, ._(parts@OCLSf))), _-_(__(t:OCL-Type, ._(capacity@OCLSf)), 1)), _or_(_or_(_and_(_->`forAll_(__(t:OCL-Type, ._(parts@OCLSf)), _|_(e, _.`oclIsKindOf`(_`)(e, Handle@devsmm))), _.`oclIsKindOf`(_`)(p:OCL-Type, Handle@devsmm)), _and_(_->`forAll_(__(t:OCL-Type, ._(parts@OCLSf)), _|_(e, _.`oclIsKindOf`(_`)(e, Head@devsmm))), _.`oclIsKindOf`(_`)(p:OCL-Type, Head@devsmm))), _and_(_->`forAll_(__(t:OCL-Type, ._(parts@OCLSf)), _|_(e, _.`oclIsKindOf`(_`)(e, Hammer@devsmm))), _.`oclIsKindOf`(_`)(p:OCL-Type, Hammer@devsmm)))))), env(empty), MODEL@:@Model) .
  ceq noconc@Collect(Set`{_`}(_;_(h:OCL-Type, t:OCL-Type, u:OCL-Type)), <_:_|_>(VAR1@:Oid, Variable@MGBehavior, _#_(_:_(name@Variable@MGBehavior, "collectTime"), _:_(value@Variable@MGBehavior, collectTime:OCL-Type))), _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(co:OCL-Type, AtomicActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, ACTION@co@ATT:String), 
          _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(L@co:MSet{OCL-Exp}, OR1@co:Oid))), co@SFS:Set{@StructuralFeatureInstance})), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@co:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, u:OCL-Type), OR1@co@SFS:Set{@StructuralFeatureInstance})))))
    = true
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(co:OCL-Type, AtomicActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, ACTION@co@ATT:String), 
            _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(L@co:MSet{OCL-Exp}, OR1@co:Oid))), co@SFS:Set{@StructuralFeatureInstance})), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@co:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, u:OCL-Type), OR1@co@SFS:Set{@StructuralFeatureInstance})))) .
  eq noconc@Collect(OIDSET@:Set, OBJSET@:Set{@Object}, MODEL@:@Model)
    = false [owise] .
  ceq mte(_`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(h:OCL-Type, HAMMER@DEVSMM@h@CLASS:Hammer@devsmm, h@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(u:OCL-Type, USER@DEVSMM@u@CLASS:User@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@u@ATT:OCL-Type), u@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object})))
    = 0
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(h:OCL-Type, HAMMER@DEVSMM@h@CLASS:Hammer@devsmm, h@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(u:OCL-Type, USER@DEVSMM@u@CLASS:User@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@u@ATT:OCL-Type), u@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
    /\ _in_(h:OCL-Type, PARTS@t@ATT:OCL-Type)
    /\ VAR1@:Oid := newId(_+_(VALUE@ids@:Int, 4))
    /\ collectTime:OCL-Type := eval(_rem_(random(_+_(VALUE@rdm@:Int, 13)), eval(5, env(empty), MODEL@:@Model)), env(empty), MODEL@:@Model)
    /\ not_(noconc@Collect(Set`{_`}(_;_(h:OCL-Type, t:OCL-Type, u:OCL-Type)), <_:_|_>(VAR1@:Oid, Variable@MGBehavior, _#_(_:_(name@Variable@MGBehavior, "collectTime"), _:_(value@Variable@MGBehavior, collectTime:OCL-Type))), MODEL@:@Model)) .
  ceq mte(_`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
        _#_(
          _:_(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type), a@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object})))
    = 0
    if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
          _#_(
            _:_(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type), a@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
    /\ eval(_.`oclIsUndefined`(`)(__(a:OCL-Type, ._(flRt@OCLSf))), env(empty), MODEL@:@Model) .
    
  crl [GenHandle@Triggering] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(hg:OCL-Type, GENHANDLE@DEVSMM@hg@CLASS:GenHandle@devsmm, 
          _#_(
            _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  =>
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(hg:OCL-Type, GENHANDLE@DEVSMM@hg@CLASS:GenHandle@devsmm, 
          _#_(
            _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "GenHandle"), 
            _:_(minTimer@AtomicActionExec@MGBehavior, MINDURATION@:Time), 
            _:_(maxTimer@ActionExec@MGBehavior, MAXDURATION@:Time), 
            _:_(executionTime@AtomicActionExec@MGBehavior, 0), 
            _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
            _:_(startingTime@ActionExec@MGBehavior, TIME@CLK@:Time), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(_;_(VAR1@:Oid, VAR2@:Oid))))), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 5))), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, hg:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "hg"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "c"))), 
        <_:_|_>(VAR1@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "prodTime"), 
            _:_(value@Variable@MGBehavior, prodTime:OCL-Type))), 
        <_:_|_>(VAR2@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "rdm"), 
            _:_(value@Variable@MGBehavior, rdm:OCL-Type)))))
  if ACTEXEC@:Oid := newId(VALUE@ids@:Int)
  /\ MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(hg:OCL-Type, GENHANDLE@DEVSMM@hg@CLASS:GenHandle@devsmm, 
        _#_(
          _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  /\ prodTime:OCL-Type := eval(_+_(_-_(
    __(hg:OCL-Type, ._(prodTime@OCLSf)), 3), _rem_(random(_+_(VALUE@rdm@:Int, 0)), eval(6, env(empty), MODEL@:@Model))), env(empty), MODEL@:@Model)
  /\ rdm:OCL-Type := eval(_rem_(random(_+_(VALUE@rdm@:Int, 1)), eval(100, env(empty), MODEL@:@Model)), env(empty), MODEL@:@Model)
  /\ eval(_and_(_>_(__(hg:OCL-Type, ._(counter@OCLSf)), 0), _<_(_+_(_->`size`(`)(__(c:OCL-Type, ._(parts@OCLSf))), _->`size`(`)(__(c:OCL-Type, ._(outParts@OCLSf)))), __(c:OCL-Type, ._(capacity@OCLSf)))), env(empty), MODEL@:@Model)
  /\ MINDURATION@:Time := toRat(eval(prodTime:OCL-Type, env(empty), MODEL@:@Model))
  /\ _in_(c:OCL-Type, OUT@hg@ATT:OCL-Type)
  /\ OR1@:Oid := newId(_+_(VALUE@ids@:Int, 1))
  /\ OR2@:Oid := newId(_+_(VALUE@ids@:Int, 2))
  /\ VAR1@:Oid := newId(_+_(VALUE@ids@:Int, 3))
  /\ VAR2@:Oid := newId(_+_(VALUE@ids@:Int, 4))
  /\ MAXDURATION@:Time := toRat(eval(prodTime:OCL-Type, env(empty), MODEL@:@Model))
  /\ not_(currentExec@GenHandle(Set`{_`}(_;_(hg:OCL-Type, c:OCL-Type)), MODEL@:@Model)) [print " -> GenHandle@Triggering \tin time " TIME@CLK@:Time] .
  
  crl [GenHandle@Realization] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(hg:OCL-Type, GENHANDLE@DEVSMM@hg@CLASS:GenHandle@devsmm, 
          _#_(
            _:_(counter@Generator@devsmm, COUNTER@hg@ATT:OCL-Type), 
            _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "GenHandle"), 
            _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
            _:_(minTimer@AtomicActionExec@MGBehavior, 0), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(executionTime@AtomicActionExec@MGBehavior, T:OCL-Type), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(_;_(VAR1@:Oid, VAR2@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, hg:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "hg"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "c"))), 
        <_:_|_>(VAR1@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "prodTime"), 
            _:_(value@Variable@MGBehavior, prodTime:OCL-Type))), 
        <_:_|_>(VAR2@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "rdm"), 
            _:_(value@Variable@MGBehavior, rdm:OCL-Type)))))
  =>
    readjust(ACTEXEC@:Oid, Set`{_`}(mt), nil, _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(hg:OCL-Type, GENHANDLE@DEVSMM@hg@CLASS:GenHandle@devsmm, 
          _#_(
            _:_(out@Machine@devsmm, update(out@Machine@devsmm, OUT@hg@ATT:OCL-Type, nil, link(c:OCL-Type, null))), 
            _:_(counter@Generator@devsmm, eval(_-_(
      __(hg:OCL-Type, ._(counter@OCLSf)), 1), env(_<-_(self, hg:OCL-Type)), MODEL@:@Model)), hg@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, update(parts@Container@devsmm, PARTS@c@ATT:OCL-Type, nil, link(h:OCL-Type, null))), c@SFS:Set{@StructuralFeatureInstance})), complete(
        <_:_|_>(h:OCL-Type, Handle@devsmm, 
            _:_(defective@Part@devsmm, eval(_<_(rdm:OCL-Type, 
      __(hg:OCL-Type, ._(defRate@OCLSf))), env(_<-_(self, h:OCL-Type)), MODEL@:@Model)))), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 1))))))
  if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(hg:OCL-Type, GENHANDLE@DEVSMM@hg@CLASS:GenHandle@devsmm, 
        _#_(
          _:_(counter@Generator@devsmm, COUNTER@hg@ATT:OCL-Type), 
          _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "GenHandle"), 
          _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
          _:_(minTimer@AtomicActionExec@MGBehavior, 0), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(executionTime@AtomicActionExec@MGBehavior, T:OCL-Type), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
          _:_(variables@ActionExec@MGBehavior, Set`{_`}(_;_(VAR1@:Oid, VAR2@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, hg:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "hg"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "c"))), 
      <_:_|_>(VAR1@:Oid, Variable@MGBehavior, 
        _#_(
          _:_(name@Variable@MGBehavior, "prodTime"), 
          _:_(value@Variable@MGBehavior, prodTime:OCL-Type))), 
      <_:_|_>(VAR2@:Oid, Variable@MGBehavior, 
        _#_(
          _:_(name@Variable@MGBehavior, "rdm"), 
          _:_(value@Variable@MGBehavior, rdm:OCL-Type)))))
  /\ h:OCL-Type := newId(_+_(VALUE@ids@:Int, 0)) [print " -> GenHandle@Realization \tin time " TIME@CLK@:Time] .
  
  crl [GenHead@Triggering] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(hg:OCL-Type, GENHEAD@DEVSMM@hg@CLASS:GenHead@devsmm, 
          _#_(
            _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  =>
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(hg:OCL-Type, GENHEAD@DEVSMM@hg@CLASS:GenHead@devsmm, 
          _#_(
            _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "GenHead"), 
            _:_(minTimer@AtomicActionExec@MGBehavior, MINDURATION@:Time), 
            _:_(maxTimer@ActionExec@MGBehavior, MAXDURATION@:Time), 
            _:_(executionTime@AtomicActionExec@MGBehavior, 0), 
            _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
            _:_(startingTime@ActionExec@MGBehavior, TIME@CLK@:Time), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(_;_(VAR1@:Oid, VAR2@:Oid))))), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 5))), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, hg:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "hg"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "c"))), 
        <_:_|_>(VAR1@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "prodTime"), 
            _:_(value@Variable@MGBehavior, prodTime:OCL-Type))), 
        <_:_|_>(VAR2@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "rdm"), 
            _:_(value@Variable@MGBehavior, rdm:OCL-Type)))))
  if ACTEXEC@:Oid := newId(VALUE@ids@:Int)
  /\ MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(hg:OCL-Type, GENHEAD@DEVSMM@hg@CLASS:GenHead@devsmm, 
        _#_(
          _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  /\ prodTime:OCL-Type := eval(_+_(_-_(
    __(hg:OCL-Type, ._(prodTime@OCLSf)), 3), _rem_(random(_+_(VALUE@rdm@:Int, 4)), eval(6, env(empty), MODEL@:@Model))), env(empty), MODEL@:@Model)
  /\ rdm:OCL-Type := eval(_rem_(random(_+_(VALUE@rdm@:Int, 5)), eval(100, env(empty), MODEL@:@Model)), env(empty), MODEL@:@Model)
  /\ eval(_and_(_>_(__(hg:OCL-Type, ._(counter@OCLSf)), 0), _<_(_+_(_->`size`(`)(__(c:OCL-Type, ._(parts@OCLSf))), _->`size`(`)(__(c:OCL-Type, ._(outParts@OCLSf)))), __(c:OCL-Type, ._(capacity@OCLSf)))), env(empty), MODEL@:@Model)
  /\ MINDURATION@:Time := toRat(eval(prodTime:OCL-Type, env(empty), MODEL@:@Model))
  /\ _in_(c:OCL-Type, OUT@hg@ATT:OCL-Type)
  /\ OR1@:Oid := newId(_+_(VALUE@ids@:Int, 1))
  /\ OR2@:Oid := newId(_+_(VALUE@ids@:Int, 2))
  /\ VAR1@:Oid := newId(_+_(VALUE@ids@:Int, 3))
  /\ VAR2@:Oid := newId(_+_(VALUE@ids@:Int, 4))
  /\ MAXDURATION@:Time := toRat(eval(prodTime:OCL-Type, env(empty), MODEL@:@Model))
  /\ not_(currentExec@GenHead(Set`{_`}(_;_(hg:OCL-Type, c:OCL-Type)), MODEL@:@Model)) [print " -> GenHead@Triggering \tin time " TIME@CLK@:Time] .
  
  crl [GenHead@Realization] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(hg:OCL-Type, GENHEAD@DEVSMM@hg@CLASS:GenHead@devsmm, 
          _#_(
            _:_(counter@Generator@devsmm, COUNTER@hg@ATT:OCL-Type), 
            _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "GenHead"), 
            _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
            _:_(minTimer@AtomicActionExec@MGBehavior, 0), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(executionTime@AtomicActionExec@MGBehavior, T:OCL-Type), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(_;_(VAR1@:Oid, VAR2@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, hg:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "hg"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "c"))), 
        <_:_|_>(VAR1@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "prodTime"), 
            _:_(value@Variable@MGBehavior, prodTime:OCL-Type))), 
        <_:_|_>(VAR2@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "rdm"), 
            _:_(value@Variable@MGBehavior, rdm:OCL-Type)))))
  =>
    readjust(ACTEXEC@:Oid, Set`{_`}(mt), nil, _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(hg:OCL-Type, GENHEAD@DEVSMM@hg@CLASS:GenHead@devsmm, 
          _#_(
            _:_(out@Machine@devsmm, update(out@Machine@devsmm, OUT@hg@ATT:OCL-Type, nil, link(c:OCL-Type, null))), 
            _:_(counter@Generator@devsmm, eval(_-_(
      __(hg:OCL-Type, ._(counter@OCLSf)), 1), env(_<-_(self, hg:OCL-Type)), MODEL@:@Model)), hg@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, update(parts@Container@devsmm, PARTS@c@ATT:OCL-Type, nil, link(h:OCL-Type, null))), c@SFS:Set{@StructuralFeatureInstance})), complete(
        <_:_|_>(h:OCL-Type, Head@devsmm, empty)), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 1))))))
  if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(hg:OCL-Type, GENHEAD@DEVSMM@hg@CLASS:GenHead@devsmm, 
        _#_(
          _:_(counter@Generator@devsmm, COUNTER@hg@ATT:OCL-Type), 
          _:_(out@Machine@devsmm, OUT@hg@ATT:OCL-Type), hg@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "GenHead"), 
          _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
          _:_(minTimer@AtomicActionExec@MGBehavior, 0), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(executionTime@AtomicActionExec@MGBehavior, T:OCL-Type), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
          _:_(variables@ActionExec@MGBehavior, Set`{_`}(_;_(VAR1@:Oid, VAR2@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, hg:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "hg"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "c"))), 
      <_:_|_>(VAR1@:Oid, Variable@MGBehavior, 
        _#_(
          _:_(name@Variable@MGBehavior, "prodTime"), 
          _:_(value@Variable@MGBehavior, prodTime:OCL-Type))), 
      <_:_|_>(VAR2@:Oid, Variable@MGBehavior, 
        _#_(
          _:_(name@Variable@MGBehavior, "rdm"), 
          _:_(value@Variable@MGBehavior, rdm:OCL-Type)))))
  /\ h:OCL-Type := newId(_+_(VALUE@ids@:Int, 0)) [print " -> GenHead@Realization \tin time " TIME@CLK@:Time] .
  
  crl [Carry@Triggering] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  =>
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "Carry"), 
            _:_(minTimer@AtomicActionExec@MGBehavior, MINDURATION@:Time), 
            _:_(maxTimer@ActionExec@MGBehavior, MAXDURATION@:Time), 
            _:_(executionTime@AtomicActionExec@MGBehavior, 0), 
            _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
            _:_(startingTime@ActionExec@MGBehavior, TIME@CLK@:Time), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(mt)))), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 3))), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "p"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "c")))))
  if ACTEXEC@:Oid := newId(VALUE@ids@:Int)
  /\ MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  /\ MINDURATION@:Time := toRat(eval(
    __(c:OCL-Type, ._(speed@OCLSf)), env(empty), MODEL@:@Model))
  /\ _in_(p:OCL-Type, PARTS@c@ATT:OCL-Type)
  /\ OR1@:Oid := newId(_+_(VALUE@ids@:Int, 1))
  /\ OR2@:Oid := newId(_+_(VALUE@ids@:Int, 2))
  /\ MAXDURATION@:Time := toRat(eval(
    __(c:OCL-Type, ._(speed@OCLSf)), env(empty), MODEL@:@Model))
  /\ not_(currentExec@Carry(Set`{_`}(_;_(p:OCL-Type, c:OCL-Type)), MODEL@:@Model)) [print " -> Carry@Triggering \tin time " TIME@CLK@:Time] .
  
  crl [Carry@Realization] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(outParts@Conveyor@devsmm, OUTPARTS@c@ATT:OCL-Type), 
            _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "Carry"), 
            _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
            _:_(minTimer@AtomicActionExec@MGBehavior, 0), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(executionTime@AtomicActionExec@MGBehavior, T:OCL-Type), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(mt)), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "p"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "c")))))
  =>
    readjust(ACTEXEC@:Oid, Set`{_`}(mt), nil, _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(outParts@Conveyor@devsmm, update(outParts@Conveyor@devsmm, OUTPARTS@c@ATT:OCL-Type, nil, link(p:OCL-Type, null))), 
            _:_(parts@Container@devsmm, update(parts@Container@devsmm, PARTS@c@ATT:OCL-Type, link(p:OCL-Type, null), nil)), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)))))
  if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
        _#_(
          _:_(outParts@Conveyor@devsmm, OUTPARTS@c@ATT:OCL-Type), 
          _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "Carry"), 
          _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
          _:_(minTimer@AtomicActionExec@MGBehavior, 0), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(executionTime@AtomicActionExec@MGBehavior, T:OCL-Type), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
          _:_(variables@ActionExec@MGBehavior, Set`{_`}(mt)), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "p"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "c"))))) [print " -> Carry@Realization \tin time " TIME@CLK@:Time] .
  
  crl [Assemble@Triggering] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(he:OCL-Type, HEAD@DEVSMM@he@CLASS:Head@devsmm, he@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(ha:OCL-Type, HANDLE@DEVSMM@ha@CLASS:Handle@devsmm, ha@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
          _#_(
            _:_(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type), 
            _:_(in@Machine@devsmm, IN@a@ATT:OCL-Type), 
            _:_(out@Machine@devsmm, OUT@a@ATT:OCL-Type), a@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(fr:OCL-Type, FAILURERATE@DEVSMM@fr@CLASS:FailureRate@devsmm, fr@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  =>
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(he:OCL-Type, HEAD@DEVSMM@he@CLASS:Head@devsmm, he@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(ha:OCL-Type, HANDLE@DEVSMM@ha@CLASS:Handle@devsmm, ha@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
          _#_(
            _:_(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type), 
            _:_(in@Machine@devsmm, IN@a@ATT:OCL-Type), 
            _:_(out@Machine@devsmm, OUT@a@ATT:OCL-Type), a@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(fr:OCL-Type, FAILURERATE@DEVSMM@fr@CLASS:FailureRate@devsmm, fr@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "Assemble"), 
            _:_(minTimer@AtomicActionExec@MGBehavior, MINDURATION@:Time), 
            _:_(maxTimer@ActionExec@MGBehavior, MAXDURATION@:Time), 
            _:_(executionTime@AtomicActionExec@MGBehavior, 0), 
            _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
            _:_(startingTime@ActionExec@MGBehavior, TIME@CLK@:Time), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid, OR3@:Oid, OR4@:Oid, OR5@:Oid, OR6@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(_;_(VAR1@:Oid, VAR2@:Oid))))), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 9))), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, he:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "he"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, ha:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "ha"))), 
        <_:_|_>(OR3@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, t:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "t"))), 
        <_:_|_>(OR4@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, a:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "a"))), 
        <_:_|_>(OR5@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "c"))), 
        <_:_|_>(OR6@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, fr:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "fr"))), 
        <_:_|_>(VAR1@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "rdm"), 
            _:_(value@Variable@MGBehavior, rdm:OCL-Type))), 
        <_:_|_>(VAR2@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "prodTime"), 
            _:_(value@Variable@MGBehavior, prodTime:OCL-Type)))))
  if ACTEXEC@:Oid := newId(VALUE@ids@:Int)
  /\ MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(he:OCL-Type, HEAD@DEVSMM@he@CLASS:Head@devsmm, he@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(ha:OCL-Type, HANDLE@DEVSMM@ha@CLASS:Handle@devsmm, ha@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
        _#_(
          _:_(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type), 
          _:_(in@Machine@devsmm, IN@a@ATT:OCL-Type), 
          _:_(out@Machine@devsmm, OUT@a@ATT:OCL-Type), a@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, c@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(fr:OCL-Type, FAILURERATE@DEVSMM@fr@CLASS:FailureRate@devsmm, fr@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  /\ rdm:OCL-Type := eval(_rem_(random(_+_(VALUE@rdm@:Int, 8)), eval(100, env(empty), MODEL@:@Model)), env(empty), MODEL@:@Model)
  /\ prodTime:OCL-Type := eval(_+_(_-_(
    __(a:OCL-Type, ._(prodTime@OCLSf)), 3), _rem_(random(_+_(VALUE@rdm@:Int, 9)), eval(6, env(empty), MODEL@:@Model))), env(empty), MODEL@:@Model)
  /\ eval(_<_(_+_(_->`size`(`)(__(c:OCL-Type, ._(parts@OCLSf))), _->`size`(`)(__(c:OCL-Type, ._(outParts@OCLSf)))), __(c:OCL-Type, ._(capacity@OCLSf))), env(empty), MODEL@:@Model)
  /\ MINDURATION@:Time := toRat(eval(prodTime:OCL-Type, env(empty), MODEL@:@Model))
  /\ _in_(he:OCL-Type, PARTS@t@ATT:OCL-Type)
  /\ _in_(ha:OCL-Type, PARTS@t@ATT:OCL-Type)
  /\ _in_(t:OCL-Type, IN@a@ATT:OCL-Type)
  /\ _in_(c:OCL-Type, OUT@a@ATT:OCL-Type)
  /\ _in_(fr:OCL-Type, FLRT@a@ATT:OCL-Type)
  /\ OR1@:Oid := newId(_+_(VALUE@ids@:Int, 1))
  /\ OR2@:Oid := newId(_+_(VALUE@ids@:Int, 2))
  /\ OR3@:Oid := newId(_+_(VALUE@ids@:Int, 3))
  /\ OR4@:Oid := newId(_+_(VALUE@ids@:Int, 4))
  /\ OR5@:Oid := newId(_+_(VALUE@ids@:Int, 5))
  /\ OR6@:Oid := newId(_+_(VALUE@ids@:Int, 6))
  /\ VAR1@:Oid := newId(_+_(VALUE@ids@:Int, 7))
  /\ VAR2@:Oid := newId(_+_(VALUE@ids@:Int, 8))
  /\ MAXDURATION@:Time := toRat(eval(prodTime:OCL-Type, env(empty), MODEL@:@Model))
  /\ not_(currentExec@Assemble(Set`{_`}(_;_(he:OCL-Type, ha:OCL-Type, t:OCL-Type, a:OCL-Type, c:OCL-Type, fr:OCL-Type)), MODEL@:@Model))
  /\ not_(notconcurrentassembles@Assemble(Set`{_`}(_;_(he:OCL-Type, ha:OCL-Type, t:OCL-Type, a:OCL-Type, c:OCL-Type, fr:OCL-Type)), __(<_:_|_>(VAR1@:Oid, Variable@MGBehavior, _#_(_:_(name@Variable@MGBehavior, "rdm"), _:_(value@Variable@MGBehavior, rdm:OCL-Type))), <_:_|_>(VAR2@:Oid, Variable@MGBehavior, _#_(_:_(name@Variable@MGBehavior, "prodTime"), _:_(value@Variable@MGBehavior, prodTime:OCL-Type)))), MODEL@:@Model)) [print " -> Assemble@Triggering \tin time " TIME@CLK@:Time] .
  
  crl [Assemble@Realization] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(he:OCL-Type, HEAD@DEVSMM@he@CLASS:Head@devsmm, he@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(ha:OCL-Type, HANDLE@DEVSMM@ha@CLASS:Handle@devsmm, ha@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
          _#_(
            _:_(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type), 
            _:_(in@Machine@devsmm, IN@a@ATT:OCL-Type), 
            _:_(out@Machine@devsmm, OUT@a@ATT:OCL-Type), a@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(fr:OCL-Type, FAILURERATE@DEVSMM@fr@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(reqResults@FailureRate@devsmm, REQRESULTS@fr@ATT:OCL-Type), fr@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "Assemble"), 
            _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
            _:_(minTimer@AtomicActionExec@MGBehavior, 0), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(executionTime@AtomicActionExec@MGBehavior, T:OCL-Type), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid, OR3@:Oid, OR4@:Oid, OR5@:Oid, OR6@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(_;_(VAR1@:Oid, VAR2@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, he:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "he"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, ha:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "ha"))), 
        <_:_|_>(OR3@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, t:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "t"))), 
        <_:_|_>(OR4@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, a:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "a"))), 
        <_:_|_>(OR5@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "c"))), 
        <_:_|_>(OR6@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, fr:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "fr"))), 
        <_:_|_>(VAR1@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "rdm"), 
            _:_(value@Variable@MGBehavior, rdm:OCL-Type))), 
        <_:_|_>(VAR2@:Oid, Variable@MGBehavior, 
          _#_(
            _:_(name@Variable@MGBehavior, "prodTime"), 
            _:_(value@Variable@MGBehavior, prodTime:OCL-Type)))))
  =>
    readjust(ACTEXEC@:Oid, Set`{_`}(_;_(he:OCL-Type, ha:OCL-Type)), nil, _`{_`}(MM@:@Metamodel, 
      __(complete(
        <_:_|_>(ham:OCL-Type, Hammer@devsmm, 
            _:_(defective@Part@devsmm, eval(_or_(_or_(
      __(ha:OCL-Type, ._(defective@OCLSf)), 
      __(he:OCL-Type, ._(defective@OCLSf))), _<_(rdm:OCL-Type, 
      __(a:OCL-Type, ._(defRate@OCLSf)))), env(_<-_(self, ham:OCL-Type)), MODEL@:@Model)))), 
        <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, update(parts@Container@devsmm, PARTS@t@ATT:OCL-Type, 
      __(link(he:OCL-Type, null), link(ha:OCL-Type, null)), nil)), t@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
          _#_(
            _:_(flRt@Assemble@devsmm, update(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type, nil, link(fr:OCL-Type, null))), 
            _:_(in@Machine@devsmm, update(in@Machine@devsmm, IN@a@ATT:OCL-Type, nil, link(t:OCL-Type, null))), 
            _:_(out@Machine@devsmm, update(out@Machine@devsmm, OUT@a@ATT:OCL-Type, nil, link(c:OCL-Type, null))), a@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, update(parts@Container@devsmm, PARTS@c@ATT:OCL-Type, nil, link(ham:OCL-Type, null))), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(fr:OCL-Type, FAILURERATE@DEVSMM@fr@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(reqResults@FailureRate@devsmm, update(reqResults@FailureRate@devsmm, REQRESULTS@fr@ATT:OCL-Type, nil, link(ham:OCL-Type, null))), fr@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 1))), 
        <_:_|_>(he:OCL-Type, HEAD@DEVSMM@he@CLASS:Head@devsmm, he@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(ha:OCL-Type, HANDLE@DEVSMM@ha@CLASS:Handle@devsmm, ha@SFS:Set{@StructuralFeatureInstance}))))
  if MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(he:OCL-Type, HEAD@DEVSMM@he@CLASS:Head@devsmm, he@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(ha:OCL-Type, HANDLE@DEVSMM@ha@CLASS:Handle@devsmm, ha@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
        _#_(
          _:_(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type), 
          _:_(in@Machine@devsmm, IN@a@ATT:OCL-Type), 
          _:_(out@Machine@devsmm, OUT@a@ATT:OCL-Type), a@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(fr:OCL-Type, FAILURERATE@DEVSMM@fr@CLASS:FailureRate@devsmm, 
        _#_(
          _:_(reqResults@FailureRate@devsmm, REQRESULTS@fr@ATT:OCL-Type), fr@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(ACTEXEC@:Oid, AtomicActionExec@MGBehavior, 
        _#_(
          _:_(action@ActionExec@MGBehavior, "Assemble"), 
          _:_(status@AtomicActionExec@MGBehavior, unfinished@ActionStatus@MGBehavior), 
          _:_(minTimer@AtomicActionExec@MGBehavior, 0), 
          _:_(endingTime@ActionExec@MGBehavior, null), 
          _:_(executionTime@AtomicActionExec@MGBehavior, T:OCL-Type), 
          _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid, OR3@:Oid, OR4@:Oid, OR5@:Oid, OR6@:Oid))), 
          _:_(variables@ActionExec@MGBehavior, Set`{_`}(_;_(VAR1@:Oid, VAR2@:Oid))), ACTEXEC@@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}, 
      <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, he:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "he"))), 
      <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, ha:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "ha"))), 
      <_:_|_>(OR3@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, t:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "t"))), 
      <_:_|_>(OR4@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, a:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "a"))), 
      <_:_|_>(OR5@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, c:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "c"))), 
      <_:_|_>(OR6@:Oid, ObjectRole@MGBehavior, 
        _#_(
          _:_(actualObject@ObjectRole@MGBehavior, fr:OCL-Type), 
          _:_(role@ObjectRole@MGBehavior, "fr"))), 
      <_:_|_>(VAR1@:Oid, Variable@MGBehavior, 
        _#_(
          _:_(name@Variable@MGBehavior, "rdm"), 
          _:_(value@Variable@MGBehavior, rdm:OCL-Type))), 
      <_:_|_>(VAR2@:Oid, Variable@MGBehavior, 
        _#_(
          _:_(name@Variable@MGBehavior, "prodTime"), 
          _:_(value@Variable@MGBehavior, prodTime:OCL-Type)))))
  /\ ham:OCL-Type := newId(_+_(VALUE@ids@:Int, 0)) [print " -> Assemble@Realization \tin time " TIME@CLK@:Time] .
  
  crl [FailureRate1@Triggering] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  =>
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(ACTEXEC@:Oid, OngoingActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "FailureRate1"), 
            _:_(maxTimer@ActionExec@MGBehavior, freeze(null)), 
            _:_(startingTime@ActionExec@MGBehavior, TIME@CLK@:Time), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(mt)), 
            _:_(upperBoundTimer@OngoingActionExec@MGBehavior, null))), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 3))), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "p"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, o:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "o")))))
  if ACTEXEC@:Oid := newId(VALUE@ids@:Int)
  /\ MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
        _#_(
          _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  /\ not_(currentExec@FailureRate1(Set`{_`}(_;_(p:OCL-Type, o:OCL-Type)), MODEL@:@Model))
  /\ eval(__(p:OCL-Type, ._(defective@OCLSf)), env(empty), MODEL@:@Model)
  /\ _in_(p:OCL-Type, REQRESULTS@o@ATT:OCL-Type)
  /\ OR1@:Oid := newId(_+_(VALUE@ids@:Int, 1))
  /\ OR2@:Oid := newId(_+_(VALUE@ids@:Int, 2)) [print " -> FailureRate1@Triggering \tin time " TIME@CLK@:Time] .
  
  crl [FailureRate2@Triggering] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  =>
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
          _#_(
            _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(ACTEXEC@:Oid, OngoingActionExec@MGBehavior, 
          _#_(
            _:_(action@ActionExec@MGBehavior, "FailureRate2"), 
            _:_(maxTimer@ActionExec@MGBehavior, freeze(null)), 
            _:_(startingTime@ActionExec@MGBehavior, TIME@CLK@:Time), 
            _:_(endingTime@ActionExec@MGBehavior, null), 
            _:_(participants@ActionExec@MGBehavior, Set`{_`}(_;_(OR1@:Oid, OR2@:Oid))), 
            _:_(variables@ActionExec@MGBehavior, Set`{_`}(mt)), 
            _:_(upperBoundTimer@OngoingActionExec@MGBehavior, null))), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 3))), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>(OR1@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, p:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "p"))), 
        <_:_|_>(OR2@:Oid, ObjectRole@MGBehavior, 
          _#_(
            _:_(actualObject@ObjectRole@MGBehavior, o:OCL-Type), 
            _:_(role@ObjectRole@MGBehavior, "o")))))
  if ACTEXEC@:Oid := newId(VALUE@ids@:Int)
  /\ MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(o:OCL-Type, FAILURERATE@DEVSMM@o@CLASS:FailureRate@devsmm, 
        _#_(
          _:_(reqResults@FailureRate@devsmm, REQRESULTS@o@ATT:OCL-Type), o@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  /\ not_(currentExec@FailureRate2(Set`{_`}(_;_(p:OCL-Type, o:OCL-Type)), MODEL@:@Model))
  /\ eval(not_(__(p:OCL-Type, ._(defective@OCLSf))), env(empty), MODEL@:@Model)
  /\ _in_(p:OCL-Type, REQRESULTS@o@ATT:OCL-Type)
  /\ OR1@:Oid := newId(_+_(VALUE@ids@:Int, 1))
  /\ OR2@:Oid := newId(_+_(VALUE@ids@:Int, 2)) [print " -> FailureRate2@Triggering \tin time " TIME@CLK@:Time] .
  
  crl [Transfer@Instantaneous] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(outParts@Conveyor@devsmm, OUTPARTS@c@ATT:OCL-Type), 
            _:_(out@Conveyor@devsmm, OUT@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  =>
    readjust(Set`{_`}(mt), nil, _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
          _#_(
            _:_(out@Conveyor@devsmm, update(out@Conveyor@devsmm, OUT@c@ATT:OCL-Type, nil, link(t:OCL-Type, null))), 
            _:_(outParts@Conveyor@devsmm, update(outParts@Conveyor@devsmm, OUTPARTS@c@ATT:OCL-Type, link(p:OCL-Type, null), nil)), c@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, update(parts@Container@devsmm, PARTS@t@ATT:OCL-Type, nil, link(p:OCL-Type, null))), t@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 4))))))
  if ACTEXEC@:Oid := newId(VALUE@ids@:Int)
  /\ MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(c:OCL-Type, CONVEYOR@DEVSMM@c@CLASS:Conveyor@devsmm, 
        _#_(
          _:_(outParts@Conveyor@devsmm, OUTPARTS@c@ATT:OCL-Type), 
          _:_(out@Conveyor@devsmm, OUT@c@ATT:OCL-Type), c@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(p:OCL-Type, PART@DEVSMM@p@CLASS:Part@devsmm, p@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  /\ eval(_and_(_<_(_->`size`(`)(__(t:OCL-Type, ._(parts@OCLSf))), __(t:OCL-Type, ._(capacity@OCLSf))), not_(_and_(_.=._(_->`size`(`)(__(t:OCL-Type, ._(parts@OCLSf))), _-_(__(t:OCL-Type, ._(capacity@OCLSf)), 1)), _or_(_or_(_and_(_->`forAll_(__(t:OCL-Type, ._(parts@OCLSf)), _|_(e, _.`oclIsKindOf`(_`)(e, Handle@devsmm))), _.`oclIsKindOf`(_`)(p:OCL-Type, Handle@devsmm)), _and_(_->`forAll_(__(t:OCL-Type, ._(parts@OCLSf)), _|_(e, _.`oclIsKindOf`(_`)(e, Head@devsmm))), _.`oclIsKindOf`(_`)(p:OCL-Type, Head@devsmm))), _and_(_->`forAll_(__(t:OCL-Type, ._(parts@OCLSf)), _|_(e, _.`oclIsKindOf`(_`)(e, Hammer@devsmm))), _.`oclIsKindOf`(_`)(p:OCL-Type, Hammer@devsmm)))))), env(empty), MODEL@:@Model)
  /\ T:OCL-Type := eval(0, env(empty), MODEL@:@Model)
  /\ _in_(t:OCL-Type, OUT@c@ATT:OCL-Type)
  /\ _in_(p:OCL-Type, OUTPARTS@c@ATT:OCL-Type)
  /\ OR1@:Oid := newId(_+_(VALUE@ids@:Int, 1))
  /\ OR2@:Oid := newId(_+_(VALUE@ids@:Int, 2))
  /\ OR3@:Oid := newId(_+_(VALUE@ids@:Int, 3)) [print " -> Transfer@Instantaneous \tin time " TIME@CLK@:Time] .
  
  crl [Collect@Instantaneous] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(h:OCL-Type, HAMMER@DEVSMM@h@CLASS:Hammer@devsmm, h@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(u:OCL-Type, USER@DEVSMM@u@CLASS:User@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, PARTS@u@ATT:OCL-Type), u@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  =>
    readjust(Set`{_`}(mt), nil, _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(h:OCL-Type, HAMMER@DEVSMM@h@CLASS:Hammer@devsmm, h@SFS:Set{@StructuralFeatureInstance}), 
        <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, update(parts@Container@devsmm, PARTS@t@ATT:OCL-Type, link(h:OCL-Type, null), nil)), t@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(u:OCL-Type, USER@DEVSMM@u@CLASS:User@devsmm, 
          _#_(
            _:_(parts@Container@devsmm, update(parts@Container@devsmm, PARTS@u@ATT:OCL-Type, nil, link(h:OCL-Type, null))), u@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 5))))))
  if ACTEXEC@:Oid := newId(VALUE@ids@:Int)
  /\ MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(h:OCL-Type, HAMMER@DEVSMM@h@CLASS:Hammer@devsmm, h@SFS:Set{@StructuralFeatureInstance}), 
      <_:_|_>(t:OCL-Type, TRAY@DEVSMM@t@CLASS:Tray@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@t@ATT:OCL-Type), t@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(u:OCL-Type, USER@DEVSMM@u@CLASS:User@devsmm, 
        _#_(
          _:_(parts@Container@devsmm, PARTS@u@ATT:OCL-Type), u@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  /\ collectTime:OCL-Type := eval(_rem_(random(_+_(VALUE@rdm@:Int, 12)), eval(5, env(empty), MODEL@:@Model)), env(empty), MODEL@:@Model)
  /\ T:OCL-Type := eval(0, env(empty), MODEL@:@Model)
  /\ _in_(h:OCL-Type, PARTS@t@ATT:OCL-Type)
  /\ OR1@:Oid := newId(_+_(VALUE@ids@:Int, 1))
  /\ OR2@:Oid := newId(_+_(VALUE@ids@:Int, 2))
  /\ OR3@:Oid := newId(_+_(VALUE@ids@:Int, 3))
  /\ VAR1@:Oid := newId(_+_(VALUE@ids@:Int, 4))
  /\ not_(noconc@Collect(Set`{_`}(_;_(h:OCL-Type, t:OCL-Type, u:OCL-Type)), <_:_|_>(VAR1@:Oid, Variable@MGBehavior, _#_(_:_(name@Variable@MGBehavior, "collectTime"), _:_(value@Variable@MGBehavior, collectTime:OCL-Type))), MODEL@:@Model)) [print " -> Collect@Instantaneous \tin time " TIME@CLK@:Time] .
  
  crl [CreateFailure@Instantaneous] :
    _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
          _#_(
            _:_(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type), a@SFS:Set{@StructuralFeatureInstance})), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  =>
    readjust(Set`{_`}(mt), nil, _`{_`}(MM@:@Metamodel, 
      __(
        <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
          _#_(
            _:_(flRt@Assemble@devsmm, update(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type, nil, link(fr:OCL-Type, null))), a@SFS:Set{@StructuralFeatureInstance})), complete(
        <_:_|_>(fr:OCL-Type, FailureRate@devsmm, empty)), 
        <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
            _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
        <_:_|_>('rdm@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@rdm@:Int, 7))), OBJSET@:Set{@Object}, 
        <_:_|_>('ids@, Counter@MGBehavior, 
            _:_(value@Counter@MGBehavior, _+_(VALUE@ids@:Int, 3))))))
  if ACTEXEC@:Oid := newId(VALUE@ids@:Int)
  /\ MODEL@:@Model := _`{_`}(MM@:@Metamodel, 
    __(
      <_:_|_>(a:OCL-Type, ASSEMBLE@DEVSMM@a@CLASS:Assemble@devsmm, 
        _#_(
          _:_(flRt@Assemble@devsmm, FLRT@a@ATT:OCL-Type), a@SFS:Set{@StructuralFeatureInstance})), 
      <_:_|_>(CLK@:Oid, Clock@MGBehavior, 
          _:_(time@Clock@MGBehavior, TIME@CLK@:Time)), 
      <_:_|_>('ids@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@ids@:Int)), 
      <_:_|_>('rdm@, Counter@MGBehavior, 
          _:_(value@Counter@MGBehavior, VALUE@rdm@:Int)), OBJSET@:Set{@Object}))
  /\ eval(_.`oclIsUndefined`(`)(__(a:OCL-Type, ._(flRt@OCLSf))), env(empty), MODEL@:@Model)
  /\ T:OCL-Type := eval(0, env(empty), MODEL@:@Model)
  /\ OR1@:Oid := newId(_+_(VALUE@ids@:Int, 1))
  /\ fr:OCL-Type := newId(_+_(VALUE@ids@:Int, 2)) [print " -> CreateFailure@Instantaneous \tin time " TIME@CLK@:Time] .
  
endm ---- end system module @DEVSMM@BEHAVIOR@
